repositories:
  - name: llm-d-modelservice
    url: https://llm-d-incubation.github.io/llm-d-modelservice/

releases:
  - name: infra-inference-scheduling
    chart: https://llm-d-incubation.github.io/llm-d-infra/
    version: v1.1.1
    installed: true
    labels:
      managedBy: llm-d-infra-installer

  - name: gaie-inference-scheduling
    chart: oci://registry.k8s.io/gateway-api-inference-extension/charts/inferencepool
    version: v0.5.1
    installed: true
    needs:
      - infra-inference-scheduling
    values:
      - gaie-inference-scheduling/values.yaml
    labels:
      managedBy: helmfile

  - name: ms-inference-scheduling
    chart: llm-d-modelservice/llm-d-modelservice
    version: v0.2.0
    installed: true
    needs:
      - infra-inference-scheduling
      - gaie-inference-scheduling
    values:
      - ms-inference-scheduling/values.yaml
    labels:
      managedBy: helmfile
