environments:
  istio:
    values:
      - ../../providers/istio.yaml
  kgateway:
    values:
      - ../../providers/kgateway.yaml
  gke:
    values:
      - ../../providers/gke.yaml

  # Default pointer to istio for now
  default:
    values:
      - ../../providers/istio.yaml

helmfiles:
  - ../../providers/helmfile.yaml.gotmpl

---

repositories:
  - name: llm-d-modelservice
    url: https://llm-d-incubation.github.io/llm-d-modelservice/
  - name: llm-d-infra
    url: https://llm-d-incubation.github.io/llm-d-infra/

releases:
  - name: infra-inference-scheduling
    namespace: llm-d-inference-scheduling
    chart: llm-d-infra/llm-d-infra
    version: v1.1.1
    installed: true

  - name: gaie-inference-scheduling
    namespace: llm-d-inference-scheduling
    chart: oci://registry.k8s.io/gateway-api-inference-extension/charts/inferencepool
    version: v0.5.1
    installed: true
    needs:
      - llm-d-inference-scheduling/infra-inference-scheduling
    values:
      - gaie-inference-scheduling/values.yaml
    labels:
      managedBy: helmfile

  - name: ms-inference-scheduling
    namespace: llm-d-inference-scheduling
    chart: llm-d-modelservice/llm-d-modelservice
    version: v0.2.0
    installed: true
    needs:
      - llm-d-inference-scheduling/infra-inference-scheduling
      - llm-d-inference-scheduling/gaie-inference-scheduling
    values:
      - ms-inference-scheduling/values.yaml
    labels:
      managedBy: helmfile
