repositories:
  - name: llm-d-modelservice
    url: https://llm-d-incubation.github.io/llm-d-modelservice/

releases:
  - name: infra-kv-events
    namespace: llm-d
    chart: oci://ghcr.io/llm-d-incubation/llm-d-infra/llm-d-infra
    version: 1.0.7
    installed: true
    labels:
      managedBy: llm-d-infra-installer

  - name: gaie-kv-events
    namespace: llm-d
    chart: oci://registry.k8s.io/gateway-api-inference-extension/charts/inferencepool
    version: v0.5.1
    installed: true
    needs:
      - llm-d/infra-kv-events
    values:
      - gaie-kv-events/values.yaml
    labels:
      managedBy: helmfile

  - name: ms-kv-events
    namespace: llm-d
    chart: llm-d-modelservice/llm-d-modelservice
    version: 0.0.19
    installed: true
    needs:
      - llm-d/infra-kv-events
      - llm-d/gaie-kv-events
    values:
      - ms-kv-events/values.yaml
    labels:
      managedBy: helmfile
