MD013:
  line_length: 5000
  code_block_line_length: 5000
MD004:
  style: dash
MD041:
  # Heading level
  level: 1
  # RegExp for matching title in front matter
  front_matter_title: "^\\s*title\\s*[:=]"

MD029: false # MD029/ol-prefix Ordered list item prefix (e.g. Style: 1/1/1)
MD010: false # MD010/no-hard-tabs Hard tabs
