repositories:
  - name: llm-d-modelservice
    url: https://llm-d-incubation.github.io/llm-d-modelservice/

releases:
  - name: infra-wide-ep
    chart: https://llm-d-incubation.github.io/llm-d-infra/
    version: v1.1.1
    installed: true
    values:
      - infra-wide-ep/values.yaml
    labels:
      managedBy: llm-d-infra-installer

  - name: ms-wide-ep
    chart: llm-d-modelservice/llm-d-modelservice
    version: v0.2.0
    installed: true
    needs:
      - infra-wide-ep
    values:
      - ms-wide-ep/values.yaml
    labels:
      managedBy: helmfile
