inferenceExtension:
  replicas: 1
  image:
    # upstream GIE epp image does NOT support PD, have to use `llm-d-inference-scheduler`
    name: llm-d-inference-scheduler
    hub: ghcr.io/llm-d
    tag: v0.2.1
    pullPolicy: Always
  extProcPort: 9002
  pluginsConfigFile: "pd-config.yaml"
  logVerbosity: 1
  pluginsCustomConfig:
    pd-config.yaml: |
      apiVersion: inference.networking.x-k8s.io/v1alpha1
      kind: EndpointPickerConfig
      plugins:
      - type: prefill-header-handler
      - type: prefill-filter
      - type: decode-filter
      - type: max-score-picker
      - type: prefix-cache-scorrer
        parameters:
          hashBlockSize: 5
          maxPrefixBlocksToMatch: 256
          lruCapacityPerServer: 31250
      - type: pd-profile-handler
        parameters:
          # ALWAYS DO PD IN THIS EXAMPLE (THRESHOLD 0)
          threshold: 0
          hashBlockSize: 5
      schedulingProfiles:
      - name: prefill
        plugins:
        - pluginRef: prefill-filter
        - pluginRef: prefix-cache-scorer
        - pluginRef: max-score-picker
      - name: decode
        plugins:
        - pluginRef: decode-filter
        - pluginRef: prefix-cache-scorer
        - pluginRef: max-score-picker
inferencePool:
  targetPortNumber: 8000
  modelServerType: vllm
  modelServers:
    matchLabels:
      llm-d.ai/inferenceServing: "true"

provider:
  name: istio

istio:
  destinationRule:
    enabled: true
    trafficPolicy:
      connectionPool:
       # These numbers were chosen arbitrarily. Istio's default max concurrent connections are set to 1024, this allows us
       # to increase the number of concurrent requests we send to lm_eval. Similarly idleTimeout, maxConnection and
       # connectTimeout were set to uncap long processing of requests and allow eval to proceed unaffected.
        http:
          http1MaxPendingRequests: 256000
          maxRequestsPerConnection: 256000
          http2MaxRequests: 256000
          idleTimeout: "900s"
          maxRequestsPerConnection: 256000
        tcp:
          maxConnections: 256000
          maxConnectionDuration: "1800s"
          connectTimeout: "900s"
      tls:
        mode: SIMPLE
        insecureSkipVerify: true
