apiVersion: v1
kind: Pod
metadata:
  name: interactive-pod
  namespace: llm-d
spec:
  containers:
    - name: benchmark-runner
      image: "docker.io/rgshaw2/interactive-pod:0.2"
      imagePullPolicy: Always
      stdin: true
      tty: true
      resources:
        requests:
          cpu: "16"
          memory: "16Gi"
        limits:
          cpu: "16"
          memory: "16Gi"