# Run these on the local machine

POD_NAME := "interactive-pod"

exec-bench NAMESPACE:
    kubectl cp Justfile.remote {{NAMESPACE}}/{{POD_NAME}}:/app/Justfile && \
    kubectl cp sweep-tp1.sh {{NAMESPACE}}/{{POD_NAME}}:/app/sweep-tp1.sh && \
    kubectl cp sweep-tp2.sh {{NAMESPACE}}/{{POD_NAME}}:/app/sweep-tp2.sh && \
    kubectl cp sweep-tp4.sh {{NAMESPACE}}/{{POD_NAME}}:/app/sweep-tp4.sh && \
    kubectl cp sweep-tp8.sh {{NAMESPACE}}/{{POD_NAME}}:/app/sweep-tp8.sh && \
    kubectl exec -it -n {{NAMESPACE}} {{POD_NAME}} -- /bin/bash

copy-results NAMESPACE FILENAME:
    kubectl cp {{NAMESPACE}}/{{POD_NAME}}:/app/{{FILENAME}} ./{{FILENAME}}
