# This values.yaml file creates the resources for Qwen/Qwen3-0.6B
multinode: false

modelArtifacts:
  uri: "hf://Qwen/Qwen3-0.6B"
  size: 20Gi
  authSecretName: "llm-d-hf-token"

routing:
  modelName: Qwen/Qwen3-0.6B
  servicePort: 8000

  proxy:
    image: "ghcr.io/llm-d/llm-d-routing-sidecar:v0.2.0-RC1"
    secure: false
    connector: nixlv2

  parentRefs:
    - group: gateway.networking.k8s.io
      kind: Gateway
      name: infra-kv-events-inference-gateway

  inferencePool:
    create: true

  httpRoute:
    create: true

  epp:
    create: true
    replicas: 1
    image: quay.io/vmaroon/llm-d-inference-scheduler:cache-tracking
    debugLevel: 4
    pluginsConfigFile: prefix-cache-tracking-config.yaml
    disableReadinessProbe: false
    disableLivenessProbe: false

    extraContainerPorts:
      - name: zmq
        containerPort: 5557
        protocol: TCP

    service:
      type: ClusterIP
      port: 9002
      targetPort: 9002
      appProtocol: grpc
      extraPorts:
        - name: zmq
          port: 5557
          targetPort: 5557
          protocol: TCP

    env:
      - name: HF_TOKEN
        valueFrom:
          secretKeyRef:
            name: llm-d-hf-token
            key: HF_TOKEN

decode:
  create: true
  replicas: 2
  containers:
  - name: "vllm"
    image: "quay.io/wseaton/vllm:llmd-multistage-6"
    modelCommand: custom
    command:
      - /bin/sh
      - '-c'
    args:
      - |
        vllm serve Qwen/Qwen3-0.6B \
        --host 0.0.0.0 \
        --port 8200 \
        --block-size 64 \
        --prefix-caching-hash-algo sha256_cbor_64bit \
        --enforce-eager \
        --kv-transfer-config '{"kv_connector":"NixlConnector", "kv_role":"kv_both"}' \
        --kv-events-config "{\"enable_kv_cache_events\":true,\"publisher\":\"zmq\",\"endpoint\":\"tcp://ms-kv-events-llm-d-modelservice-epp:5557\",\"topic\":\"kv@${POD_IP}@Qwen/Qwen3-0.6B\"}" \
    env:
      - name: PYTHONHASHSEED
        value: "42"
      - name: POD_IP
        valueFrom:
          fieldRef:
            apiVersion: v1
            fieldPath: status.podIP
      - name: CUDA_VISIBLE_DEVICES
        value: "0"
      - name: UCX_TLS
        value: "cuda_ipc,cuda_copy,tcp"
      - name: VLLM_NIXL_SIDE_CHANNEL_HOST
        valueFrom:
          fieldRef:
            fieldPath: status.podIP
      - name: VLLM_NIXL_SIDE_CHANNEL_PORT
        value: "5557"
      - name: VLLM_LOGGING_LEVEL
        value: DEBUG
    ports:
      - containerPort: 5557
        protocol: TCP
    resources:
      limits:
        nvidia.com/gpu: "1"
      requests:
        nvidia.com/gpu: "1"
    mountModelVolume: true
    volumeMounts:
    - name: metrics-volume
      mountPath: /.config
    - name: torch-compile-cache
      mountPath: /.cache
  volumes:
  - name: metrics-volume
    emptyDir: {}
  - name: torch-compile-cache
    emptyDir: {}

# The prefill replica is disabled via 'create: false' since pd is not
# enabled for this configuration. Advanced P/D examples will follow later.
prefill:
  create: false
