multinode: false

modelArtifacts:
  uri: "hf://random"
  name: random
  size: 5Mi

routing:
  modelName: random
  servicePort: 8000
  parentRefs:
    - group: gateway.networking.k8s.io
      kind: Gateway
      # name: infra-sim-inference-gateway # set in helmfile, based on infra release name

  proxy:
    image: ghcr.io/llm-d/llm-d-routing-sidecar:v0.2.0
    connector: nixlv2
    secure: false

  inferencePool:
    create: false
    # name: gaie-sim # set in helmfile, based on gaie release name. Affects httpRoute backend ref and EPP deployment, inferencepool if create through ms, inferencemodel if created (deprecated in latest)

  httpRoute:
    create: true

  epp:
    create: false

decode:
  create: true
  replicas: 2
  monitoring:
    podmonitor:
      enabled: true
      portName: "metrics"  # decode vLLM service port (from routing.proxy.targetPort)
      path: "/metrics"
      interval: "30s"
  containers:
  - name: "vllm"
    image: "ghcr.io/llm-d/llm-d-inference-sim:v0.3.0"
    modelCommand: imageDefault
    ports:
      - containerPort: 8200
        name: metrics
        protocol: TCP
      - containerPort: 5557
        protocol: TCP
    mountModelVolume: true
    volumeMounts:
    - name: metrics-volume
      mountPath: /.config
    startupProbe:
      httpGet:
        path: /health
        port: 8200
      initialDelaySeconds: 15
      periodSeconds: 30
      timeoutSeconds: 5
      failureThreshold: 60
    livenessProbe:
      httpGet:
        path: /health
        port: 8200
      periodSeconds: 10
      timeoutSeconds: 5
      failureThreshold: 3
    readinessProbe:
      httpGet:
        path: /health
        port: 8200
      periodSeconds: 5
      timeoutSeconds: 2
      failureThreshold: 3
  volumes:
  - name: metrics-volume
    emptyDir: {}

# P/D dissagg not supported, only create decode
prefill:
  create: false
