repositories:
  - name: llm-d-modelservice
    url: https://llm-d-incubation.github.io/llm-d-modelservice/

releases:
  - name: infra-simple
    namespace: llm-d
    chart: oci://ghcr.io/llm-d-incubation/llm-d-infra/llm-d-infra
    version: 1.0.5
    installed: true
    labels:
      managedBy: llm-d-infra-installer

  - name: ms-simple
    namespace: llm-d
    # chart: llm-d-modelservice/llm-d-modelservice
    # version: 0.0.16
    # waiting on: https://github.com/llm-d-incubation/llm-d-modelservice/pull/46
    chart: ../../../../../llm-d-modelservice/charts/llm-d-modelservice/
    installed: true
    needs:
      - llm-d/infra-simple
    values:
      - ms-simple/values.yaml
    labels:
      managedBy: helmfile
    hooks:
      - events: [ "postsync" ]
        command: bash
        args:
          - -c
          - |
            echo "Patching HTTPRoute to trigger reconciliation..."
            kubectl patch httproute ms-simple-llm-d-modelservice \
              -n llm-d \
              -p '{"metadata":{"labels":{"inferencepool":"ms-simple-llm-d-modelservice"}}}' \
              --type=merge
