gateway:
  gatewayClassName: istio
  gatewayParameters:
    logLevel: error # drop log level to improve performance
    resources: # increase default gateway envoy container resources for higher performance
      limits:
        cpu: "4"
        memory: 4Gi
      requests:
        cpu: "1"
        memory: 1Gi
