repositories:
  - name: llm-d-modelservice
    url: https://llm-d-incubation.github.io/llm-d-modelservice/

releases:
  - name: infra-pd
    chart: https://llm-d-incubation.github.io/llm-d-infra/
    version: v1.1.1
    installed: true
    values:
      - infra-pd/values.yaml
    labels:
      managedBy: llm-d-infra-installer

  - name: gaie-pd
    chart: oci://registry.k8s.io/gateway-api-inference-extension/charts/inferencepool
    version: v0.5.1
    installed: true
    needs:
      - infra-pd
    values:
      - gaie-pd/values.yaml
    labels:
      managedBy: helmfile

  - name: ms-pd
    chart: llm-d-modelservice/llm-d-modelservice
    version: v0.2.0
    installed: true
    needs:
      - infra-pd
      - gaie-pd
    values:
      - ms-pd/values.yaml
    labels:
      managedBy: helmfile
