inferenceExtension:
  replicas: 1
  image:
    # Either image will work, you just need to bring the correct plugins per image. In this example we will bring the upstream default plugin
    ###################
    name: llm-d-inference-scheduler
    hub: ghcr.io/llm-d
    tag: v0.3.0-rc.1
    ###################
    # name: epp
    # hub: registry.k8s.io/gateway-api-inference-extension
    # tag: v1.0.0-rc.4
    ###################
    pullPolicy: Always
  extProcPort: 9002
  pluginsConfigFile: "default-plugins.yaml"
  extraContainerPorts: []
  extraServicePorts: []
  flags:
    - name: "pool-group"
      value: "inference.networking.x-k8s.io"
inferencePool:
  apiVersion: inference.networking.x-k8s.io/v1alpha2 # use old API version for inference
  targetPortNumber: 8000
  modelServerType: vllm
  modelServers:
    matchLabels:
      llm-d.ai/inferenceServing: "true"
provider:
  name: none
