# repositories:
#   - name: llm-d-modelservice
#     url: https://llm-d-incubation.github.io/llm-d-modelservice/

releases:
  - name: infra-pd-mini
    namespace: llm-d
    chart: oci://ghcr.io/llm-d-incubation/llm-d-infra/llm-d-infra
    version: 1.0.5
    installed: true
    labels:
      managedBy: llm-d-infra-installer

  - name: gaie-pd-mini
    namespace: llm-d
    chart: oci://us-central1-docker.pkg.dev/k8s-staging-images/gateway-api-inference-extension/charts/inferencepool
    version: v0.5.0-rc.2
    installed: true
    needs:
      - llm-d/infra-pd-mini
    values:
      - gaie-pd-mini/values.yaml
    labels:
      managedBy: helmfile

  - name: ms-pd-mini
    namespace: llm-d
    # chart: llm-d-modelservice/llm-d-modelservice
    chart: ../../../../llm-d-modelservice-charts/charts/llm-d-modelservice/
    version: 0.0.15
    installed: true
    needs:
      - llm-d/infra-pd-mini
      - llm-d/gaie-pd-mini
    values:
      - ms-pd-mini/values.yaml
    labels:
      managedBy: helmfile
