apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: hf-model-pvc
spec:
  accessModes:
    - ReadWriteMany   # Change to ReadWriteMany if your storage class supports it
  resources:
    requests:
      storage: 250Gi
